### ISSUE TITLE
The addon does not install, in the console writes that it was successfully installed

### ISSUE THREAD

**Issue by LainIwakura98** [makehumancommunity/mpfb2#55] opened 2022-10-01 20:36 UTC
The addon does not install, in the console writes that it was successfully installed. It worked fine in 3.1.

**Platform and versions**
 - OS: Is this windows
 - Version of Blender:3.2 and 3.3
 - Version of MPFB 1 and 2 alpha

**Comment by joepal1976** [comment] 2022-10-02 07:30
As the plugin works fine in both 3.2 and 3.3 for me, I have not enough to go on to debug this. 

Can you provide the following: 

- A screenshot of the addon preferences window with the mpfb2 addon preferences section expanded
- A screenshot of the system console window as it looks after having started blender. You should be able to find this in the "window" menu, under "toggle system console"
- If you can find it, a screenshot of any mpfb directory that has been created under your blender user settings. Depending on how you installed blender these can be tricky to find though. They're usually under C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.xx somewhere, if they have been created at all

**Comment by LainIwakura98** [comment] 2022-10-02 09:10
![image](https://user-images.githubusercontent.com/39774833/193446826-cf2a62ea-fda3-45a6-8643-4f1fdbdafa64.png)
![image](https://user-images.githubusercontent.com/39774833/193446846-e8748182-c200-4c07-90a5-4573e0191d8a.png)

**Comment by joepal1976** [comment] 2022-10-03 16:42
Ok, I don't see any obvious explanation to what happens. I'll try some experiments and see if I can provoke a similar behavior, but it will be a day or two.

Meanwhile, can you think of anything which might be different in your environment that might have an influence?

**Comment by OfAllTheBars** [comment] 2022-10-03 17:50
I have seen this behaviour - maybe even with a version of mpfb2.  I suggest you check that the .zip file of the addon has the correct content.  Mine looks like this... (the file dates will most likely differ as I think I am still running an old version)...

![image](https://user-images.githubusercontent.com/16051751/193644248-074e792e-dabd-45c1-9d4a-a204fadeb275.png)

[You can reproduce the error by creating a .zip file with a single (empty) .txt file.  It appears to install but does not get added to the addons list.  Perhaps I should report this as a Blender bug!

Russell

**Comment by LainIwakura98** [comment] 2022-10-03 21:35
I download from tuxfamily and it just works.. version 2.0.3 its alpha 2 right or mpfb last?

**Comment by joepal1976** [comment] 2022-10-04 05:54
@OfAllTheBars thanks, I'll take a look at the git repo. The releases directory is very much not relevant anymore.

@LainIwakura98 Good to hear that it works. The last number in the version string is the alpha number at the moment. So 2.0.3 is what to become 2.0-alpha3. It currently contains a few more bugfixes but is otherwise mostly identical to alpha2.

**Comment by joepal1976** [comment] 2022-11-09 10:19
Closing this as I think all action points have been adressed.

**Closed by joepal1976** 2022-11-09 10:19 UTC
Labels: bug
