### ISSUE TITLE
Several code parts still use modifier move without context override, causing a crashes in blender 4

### ISSUE THREAD

**Issue by NCGraphics** [makehumancommunity/mpfb2#177] opened 2024-03-12 02:36 UTC
**Describe the bug**
This error occurs whem I try to import from MakeHuman program 1.2

**Checklist**
Yes

An unhandled error was encountered. Please provide this info in an error report:

CONTEXT
-------
context .............. : <bpy_struct, Context at 0x000002B7F3B15088>
scene ................ : <bpy_struct, Scene("Scene") at 0x000002B7ADBF2048>
active_object ........ : <bpy_struct, Object("Blue Coveralls") at 0x000002B7ADF8C108>
active_object_mode ... : OBJECT
active_object_type ... : Skeleton

OPERATOR
--------
name ................. : MPFB_OT_importer_import_body
label...... .......... : Import human

SYSTEM
------
blender_version ...... : (4, 0, 2)
blender_version_string : 4.0.2
python_version ....... : 3.10.13 (main, Sep 20 2023, 07:33:17) [MSC v.1928 64 bit (AMD64)]
platform ............. : Windows-10-10.0.22631-SP0
platform system....... : Windows
platform release...... : 10

MPFB
----
version .............. : (2, 0, 4)
build ................ : 20240311
data dir ............. : C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\data
mpfb dir ............. : C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb
user dir ............. : C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\mpfb

ERROR
-----
type ................. : ValueError
message .............. : 1-2 args execution context is supported

STACK TRACE
-----------
Traceback (most recent call last):
  File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\ui\mpfboperator.py", line 89, in execute
    return self.hardened_execute(context)
  File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\ui\importer\operators\importhuman.py", line 471, in hardened_execute
    self._construct_basemesh_and_or_rig_if_required(importer)
  File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\ui\importer\operators\importhuman.py", line 79, in _construct_basemesh_and_or_rig_if_required
    (obj, parent) = temp["socket_body"].as_blender_mesh_object()
  File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\entities\socketobject\socketbodyobject.py", line 226, in as_blender_mesh_object
    bpy.ops.object.modifier_move_up({'object': obj}, modifier=modifier.name)
  File "C:\SDXC Card\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\SDXC Card\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Platform and versions**
 - OS: Windows 11
 - Version of Blender 4.0.2
 - Version of MPFB mpfb2-latest.zip downloaded 3/11/2024

**Comment by joepal1976** [comment] 2024-03-12 14:01
This is a more general problem. There are several places in the code base where the old inline style object-context parameter is used. 

It's easily solvable since there's a working generic method for the same operation in ModifierService, but ideally all places should be fixed while we're at it.

**Comment by joepal1976** [comment] 2024-03-16 13:47
Now the online import from MakeHuman should work then a rig is selected. 

This will appear in tomorrow's build.

**Comment by joepal1976** [comment] 2024-05-07 05:57
Assumed to be working as intended.

**Closed by joepal1976** 2024-05-07 05:57 UTC
Labels: bug, fix exists - testing needed
