### ISSUE TITLE
Blender crashes when rendering eye texture

### ISSUE THREAD

**Issue by mikecarey134** [makehumancommunity/mpfb2#125] opened 2023-07-22 23:48 UTC
**Describe the bug**
Blender crashes when moving to texture/rendered eyes only happens when Procedural Eyes is checked in Library settings

**logs**
error message when running from console
Could not read preference mpfb_user_data

**Platform and versions**
 - OS: Linux Kubuntu 23.04
 - Version of Blender 3.4.1
 - Version of MPFB downloaded on 7/22/2023

**Comment by Vidyut** [comment] 2023-07-27 04:26
I don't know if this is related, but I can't get the eyes to work with Rigify. I could swear they used to work before. Now they pop out of the head or go up into the skull, etc. But this could be me messing up things - I'm not very experienced with blender, animation or MPFB, just ... street smart.

**Comment by joepal1976** [comment] 2023-07-27 09:47
I can't trigger this (the crash) with mostly the same setup. I tried:

- New human from scratch
- Check "procedural eyes" in library settings
- Load low-poly eyes
- Move to rendered viewport mode

If you are able to trigger this again, can you attach a full log file? There is a button "developer" -> "export log" to save it as a text file.

**Comment by mikecarey134** [comment] 2023-07-27 12:13
There must have recently been a change on the blender side because now when I do the same steps the eyes just remain invisible without a crash and only show up when I load a material other than the default one. I attached the trace log here.
[log.txt](https://github.com/makehumancommunity/mpfb2/files/12183127/log.txt)

**Comment by tsiegleauq** [comment] 2023-08-31 17:59
I can reproduce this on blender Blender 3.6.0 build date: 2023-07-07 on Arch Linux with MPFB2 nightlx 31.08.2023.
While I am in Solid viewport Shading everything is fine, changing to Vierport Shading crashes blender due to the eyes.


> I can't trigger this (the crash) with mostly the same setup. I tried:
> 
> New human from scratch
> **Check "procedural eyes" in library settings**
> Load low-poly eyes
> Move to rendered viewport mode

I do not know where to find the check for procedural eyes, I did not change anything post installation of MPFB2 and the base asset packs and it crashes every time.

**Comment by joepal1976** [comment] 2023-09-01 09:13
Thanks, that gives me more to go on. 

Do you happen to have the blender crash log? When blender itself crashes, it should write a dump of its internal state somewhere, I think in /tmp.

Also, if you have the time, could you check if the crash persists with these tested separately:

- If loading "high-poly" eyes rather than "low-poly"
- Unchecking the procedural eyes checkbox, which is under "apply assets" -> "library settings" before loading any eye
- Using the rendering mode you didn't test before (ie if the crash was with eevee previously, does it work with cycles?)

**Comment by joepal1976** [comment] 2023-09-08 09:14
Still can't trigger this. Tried all combinations I could think of for:

- blender 3.4.1 / blender 3.6.0
- eevee / cycles
- low poly / high poly
- procedural / non-procedural

Unfortunately I'm stuck here until I get more info to go on. I'll need a blender crash log (ie blender's log, not the mpfb log) and information about the system hardware. For the latter part: what graphics card are you using? Is it a discreet graphics card, an onboard graphics card (such as in many laptops) or an integrated GPU/CPU (such as in an intel i7 processor) ?

**Comment by tsiegleauq** [comment] 2023-09-20 19:24
Cannot reproduce it anymore on Belnder 3.6.2 and Kernel 6.5.3
I did not update mpfb2 and now the eyes are rendering fine for me. No more crashes.

**Comment by joepal1976** [comment] 2023-11-10 11:30
Closing this for now. Re-open if you still have the problem, preferrably combined with attaching a blender crash log.

**Closed by joepal1976** 2023-11-10 11:30 UTC
Labels: bug
