### ISSUE TITLE
Makehuman Import Fails with Error: Object 'xxxx' already in collection 'Collection'

### ISSUE THREAD

**Issue by bazza2jw** [makehumancommunity/mpfb2#145] opened 2023-09-22 12:09 UTC
**Describe the bug**
Fails when importing from Makehuman with "Error: Object 'pauline' already in collection 'Collection'"

STACK TRACE
-----------
Traceback (most recent call last):
  File "/home/barry/.config/blender/3.6/scripts/addons/mpfb/ui/mpfboperator.py", line 89, in execute
    return self.hardened_execute(context)
  File "/home/barry/.config/blender/3.6/scripts/addons/mpfb/ui/importer/operators/importhuman.py", line 471, in hardened_execute
    self._construct_basemesh_and_or_rig_if_required(importer)
  File "/home/barry/.config/blender/3.6/scripts/addons/mpfb/ui/importer/operators/importhuman.py", line 79, in _construct_basemesh_and_or_rig_if_required
    (obj, parent) = temp["socket_body"].as_blender_mesh_object()
  File "/home/barry/.config/blender/3.6/scripts/addons/mpfb/entities/socketobject/socketbodyobject.py", line 219, in as_blender_mesh_object
    ObjectService.link_blender_object(obj, collection=collection, parent=obj_parent)
  File "/home/barry/.config/blender/3.6/scripts/addons/mpfb/services/objectservice.py", line 153, in link_blender_object
    collection.objects.link(object_to_link)
RuntimeError: Error: Object 'pauline' already in collection 'Collection'

**Comment by joepal1976** [comment] 2023-09-22 12:46
This sounds like #137, which was fixed two weeks ago. Are you using a recent nightly build of mpfb?

**Comment by joepal1976** [comment] 2023-10-15 11:04
No more info, assuming this is a duplicate of #137.

**Closed by joepal1976** 2023-10-15 11:04 UTC
Labels: bug
